# Generated by Django 4.0.4 on 2022-05-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_attachment_socialnetwork_post_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ok_post',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tg_post',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='vk_post',
            field=models.BooleanField(default=True),
        ),
    ]
