# Generated by Django 4.0.4 on 2022-05-27 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_ok_post_post_tg_post_post_vk_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='social_networks',
        ),
        migrations.DeleteModel(
            name='SocialNetwork',
        ),
    ]
