# Generated by Django 3.2 on 2022-06-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20220605_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkinfo',
            name='access_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
