# Generated by Django 3.2 on 2022-06-08 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20220606_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='vk_post',
        ),
    ]
