# Generated by Django 3.2 on 2022-06-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20220609_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegraminfo',
            name='chat_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
