version: '3.7'
services:
  web:
    build:
      context: ./onepost_backend
      dockerfile: Dockerfile
    command: gunicorn onepost.wsgi:application -c ./gunicorn.conf.py
    expose:
      - 8000
    volumes:
      - static_volume:/home/onepost/onepost_backend/staticfiles
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  redis:
    image: redis:alpine

  celery:
    build: ./onepost_backend
    command: celery -A onepost worker -l info
    env_file:
      - ./.env.prod
    depends_on:
      - redis
      - web

  nginx:
    build: ./nginx
    expose:
      - 8080
    ports:
      - 80:8080
    volumes:
      - static_volume:/home/onepost/onepost_backend/staticfiles
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
