version: '3.7'
services:
  web:
    build: ./onepost_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./onepost_backend/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=onepost
      - POSTGRES_PASSWORD=onepost
      - POSTGRES_DB=onepost

  redis:
    image: redis:alpine
  celery:
    build: ./onepost_backend
    command: celery -A onepost worker -l info
    volumes:
      - ./onepost_backend/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis
  celery-beat:
    build: ./onepost_backend
    command: celery -A onepost worker -l info
    volumes:
      - ./onepost_backend/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis

volumes:
  postgres_data:
