# Generated by Django 3.2 on 2022-06-06 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_vkinfo_access_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramAccount',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_draft',
        ),
        migrations.DeleteModel(
            name='VKAccount',
        ),
    ]
