# Generated by Django 3.2 on 2022-06-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_remove_post_vk_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tg_message_chat_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tg_message_id',
            field=models.IntegerField(null=True),
        ),
    ]
