# Generated by Django 3.2 on 2022-06-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_alter_telegraminfo_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tg_message_chat_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tg_message_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
