# Generated by Django 3.2 on 2022-06-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20220609_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vk_post',
            field=models.BooleanField(default=True),
        ),
    ]
