# Generated by Django 3.2 on 2022-06-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_post_vk_post'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author'], name='posts_post_author__19d68b_idx'),
        ),
    ]
