name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
        
      - name: Prepare
        run: |
          sudo apt-get install python3 pip
          pip3 install -r ./onepost_backend/requirements.txt
          
      - name: Test
        run: python3 ./onepost_backend/manage.py test
        
  build_back:
  
    runs-on: ubuntu-latest
    
    needs: test

    steps:

      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx for Backend
        id: buildx_backend
        uses: docker/setup-buildx-action@v1

      - name: Build and push backend
        id: docker_build_backend
        uses: docker/build-push-action@v2
        with:
          context: ./onepost_backend/
          file: ./onepost_backend/Dockerfile.prod
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/onepost_backend:latest
    
  build_nginx:
    runs-on: ubuntu-latest
    
    needs: test
    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Set up Docker Buildx for nginx
        id: buildx_nginx
        uses: docker/setup-buildx-action@v1
          
      - name: Build and push nginx
        id: docker_build_nginx
        uses: docker/build-push-action@v2
        with:
          context: ./nginx/
          file: ./nginx/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/onepost_nginx:latest

  deploy:
    name: Deploy project to GCP
    runs-on: ubuntu-latest
    needs: [build_back, build_nginx]
    steps:
      - name: Copy SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/gcloud
          chmod 700 ~/.ssh/gcloud
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      - name: Reload Project
        run: |
          ssh -i ~/.ssh/gcloud vadickozlov@104.196.231.137 "sh deploy.sh"
